### PR TITLE
Add Don't Ask Software's DAC card for S.A.M.

### PR DESCRIPTION
**Pull request by zellyn**
Adds a general-purpose Digital-to-Analog converter, distributed with
Don't Ask Software's Software Automatic Mouth (S.A.M.).

### CODE REVIEW

**Comment by tobier** [comment]
Just looking over the implementation it looks good; I'll have to test it when I get home today.

Any good ways for me to test it in the emulator more than just adding the device? :-)

**Comment by zellyn** [comment]
Drag the new device to slot 2, then boot the SAM disk: http://mirrors.apple2.org.za/Apple%20II%20Documentation%20Project/Interface%20Cards/Speech/Don't%20Ask%20Software%20Automated%20Mouth/Disk%20Images/S.A.M.%20-%20Hardware%20Version.po

You should be able to run the various programs, like "run speeches", etc.

**Comment by tobier** [comment]
I can't seem to load the SAM disk image (or any image?); I haven't used the emulator in over a year so maybe it's a problem on my end. I insert the image and reset the Apple 2, but nothing is loaded. Run Speeches doesn't seem to work either.

**Comment by zellyn** [comment]
Did you `PR#6` from the basic prompt or `6<ctrl-p` from monitor?

**Comment by tobier** [comment]
Thanks, I got it to work. My only experience with Apple 2 is in this emulator so my knowledge is a bit limited.

**Pull request merged**
